INSTALL=install
PREFIX?=/usr/local
BINDIR?=$(PREFIX)/bin

default:

install:
	$(INSTALL) watch_outstanding.py $(DESTDIR)$(BINDIR)/watch_outstanding_databursts
	$(INSTALL) broker_throughput.py $(DESTDIR)$(BINDIR)/broker_throughput.py
	$(INSTALL) broker_throughput $(DESTDIR)$(BINDIR)/broker_throughput
