INSTALL?=install
BINDIR?=/usr/local/bin

default:

install:
	$(INSTALL) watch_outstanding.py $(BINDIR)/watch_outstanding_databursts
	$(INSTALL) broker_throughput.py $(BINDIR)/broker_throughput.py
	$(INSTALL) broker_throughput $(BINDIR)/broker_throughput
